---
- hosts: k8s_masters
  vars_files:
    - group_vars/all.yml
#  become: yes

- name: Verify limit is set
fail:
  msg: 'Usage: ansible-playbook -i inventory/k8shosts add-node.yml --limit <FQDN>'
when: ansible_limit is not defined
run_once: true

  roles:
    - prerequisites
    - setup-nodes
    - add-masters
    - encrypt-secrets

- hosts: k8s_worker_nodes
  vars_files:
    - group_vars/all.yml
#  become: yes

  roles:
    - prerequisites
    - setup-nodes
    - add-worker