---
- hosts: k8s_master_0
  vars_files:
    - group_vars/all.yml
  become: yes

  roles:
    - prerequisites
    - setup-nodes
    - first-master

- hosts: k8s_master_nodes
  vars_files:
    - group_vars/all.yml
  become: yes

  roles:
    - prerequisites
    - setup-nodes
    - masters

- hosts: k8s_worker_nodes
  vars_files:
    - group_vars/all.yml
  become: yes

  roles:
    - prerequisites
    - setup-nodes
    - workers

- hosts: k8s_etcd
  vars_files:
    - group_vars/all.yml
  become: yes

  roles:
    - encrypt-secrets

#- hosts: k8s_master_0
#  vars_files:
#    - group_vars/all.yml
#  become: yes

#  roles:
#    - smoke-test