---
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  
  - name: Add the br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: Add the overlay module
    modprobe:
      name: overlay
      state: present

  - name: Creating a containerd.conf file for Kubernetes
    file:
     path: /etc/modules-load.d/containerd.conf
     state: touch

  - name: Letting iptables see bridged traffic
    blockinfile:
     path: /etc/modules-load.d/containerd.conf
     block: |
      overlay
      br_netfilter

  - name: Creating a containerd.conf file for Kubernetes
    file:
     path: /etc/modules-load.d/99-kubernetes-cri.conf
     state: touch

  - name: Letting iptables see bridged traffic
    blockinfile:
     path: /etc/modules-load.d/99-kubernetes-cri.conf
     block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

  - name: Apply sysctl params without reboot
    shell: sudo sysctl --system
  
  - name: Add DockerCE repository
    shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Installing required packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Configure & restart containerd
    shell: |
      sudo mkdir -p /etc/containerd
      sudo containerd config default | sudo tee /etc/containerd/config.toml
      sudo systemctl restart containerd

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports if ('k8s_master_nodes' in group_names) else worker_ports }}"

  - name: Masquerade external zone
    firewalld: zone=public masquerade=yes permanent=true state=enabled
  
  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

  - name: Enabling ipv4 forward Firewall Rule
    shell: "echo '1' > /proc/sys/net/ipv4/ip_forward"

  - name: Stop & disable NetworkManager service
    systemd:
      name: NetworkManager
      state: stopped
      enabled: no